version: '3.8'
services:
  caddy:
    image: "caddy:latest"
    ports:
      - "8080:80"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./src:/srv
    networks:
      - default
  mysql:
    image: "mysql:latest"
    ports:
      - "6033:3306"
    volumes:
      - dbdata:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - backend
    env_file:
      - .env
  php:
    build: ./docker/php
    restart: unless-stopped
    working_dir: /srv
    volumes:
      - ./src:/srv
    networks:
      - default
      - backend

volumes:
  dbdata:
  caddy_config:
  caddy_data:
networks:
  backend:
    internal: true